project:
  type: website
  output-dir: docs

website:
  title: "Kumar H website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    toc: true
