---
title: "Kumar H"
---

## Bio
I am a data scientist with experience in economics and policy research.

As of Spring 2024, I am graduating with a MS in Data Science and Public Policy from Georgetown University, Washington DC; where I currently work as a graduate research assistant at the 
[Massive Data Institute](https://mdi.georgetown.edu/). My research interests and project experience are focused 
on energy, climate and the application of deep learning and Large Language Models (LLMs) to policy issues.

**Jan 2024**: Check out the [Wetland Impact Tracker](https://climateprogramportal.org/wetlands-impact-tracker/) we designed in collaboration with Atlas Public Policy and EPIC!

Check out my portfolio and research projects on the other pages. [This site is currently under improvement, and more information will be added.]


## Contact Information

**Email**: hk939@georgetown.edu, hkumar747@gmail.com

**Github**: [hkumar747](https://github.com/hkumar747)

**Linkedin**: [Profile](https://www.linkedin.com/in/himangshu-kumar/)
